# Generated by Django 4.2.16 on 2024-09-20 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("traffic_api", "000X_auto_populate_geom"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="speedreading",
            options={"managed": False},
        ),
    ]
