# Generated by Django 4.2.16 on 2024-09-20 17:11

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RoadSegment",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("long_start", models.FloatField()),
                ("lat_start", models.FloatField()),
                ("long_end", models.FloatField()),
                ("lat_end", models.FloatField()),
                ("length", models.FloatField()),
                (
                    "geom_start",
                    django.contrib.gis.db.models.fields.PointField(
                        blank=True, null=True, srid=4326
                    ),
                ),
                (
                    "geom_end",
                    django.contrib.gis.db.models.fields.PointField(
                        blank=True, null=True, srid=4326
                    ),
                ),
            ],
            options={
                "db_table": "traffic_speed",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="SpeedInterval",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("low_speed", models.FloatField(default=20)),
                ("medium_speed", models.FloatField(default=50)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="SpeedReading",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("speed", models.FloatField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "road_segment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="speed_readings",
                        to="traffic_api.roadsegment",
                    ),
                ),
            ],
        ),
    ]
