# Generated by Django 4.2.16 on 2024-09-20 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("traffic_api", "0001_alter_speedreading_options"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="roadsegment",
            table="nome_da_tabela_road_segment",
        ),
        migrations.AlterModelTable(
            name="speedreading",
            table="traffic_speed",
        ),
    ]
