# Generated by Django 4.2.16 on 2024-09-20 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("traffic_api", "0003_alter_roadsegment_table"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="speedreading",
            options={},
        ),
    ]
