# Generated by Django 4.2.16 on 2024-09-21 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("traffic_api", "0004_alter_speedreading_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="speedreading",
            options={"managed": False},
        ),
    ]
